## pandas biblioteca

In [55]:
# importando biblioteaca
import pandas as pd # pandas agora tem o nome de pd
# ele vai ler o arquivo conforme a seu formato read_nome do formato ex: read_excel,read_html,read_clipboard
# então melhor saber que formato se encontra o arquivo   
# ctrl + c = copia; ctrl + v = cola;                                
df = pd.read_csv(r"C:\Users\user\Desktop\grafico\Athlete\athlete_events.csv") # de ctrl + c no local do arq e cole dentro das aspas
# o r serve para não dar error 
# .head() sem  numero mostra 5 linhas 
df.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [56]:
#  mas ele pode mostrar a quatidade de linhas que você quiser
df.head(0)
# como você pode ver o titulo esta em ingles, mas tem como mudar isso 

Empty DataFrame
Columns: [ID, Name, Sex, Age, Height, Weight, Team, NOC, Games, Year, Season, City, Sport, Event, Medal]
Index: []

In [57]:
#  NOC = Sigla( National Olympic Committee) traduzido = Comitês Olímpicos Nacionais (CON)
 
dif = df.rename(columns={'Name':'Nome','Sex':"Sexo","Age":'Idade','Height':"Peso","Weight":'Altura',"Team":'Time','NOC':"CON","Games":'Jogos',"Year":'Ano','Season':"Temporada","City":'Cidade','Sport':"Esporte",'Event':"Evento","Medal":'Medalha'})
dif.head()

ID                      Nome Sexo  Idade   Peso  Altura            Time  \
0   1                 A Dijiang    M   24.0  180.0    80.0           China   
1   2                  A Lamusi    M   23.0  170.0    60.0           China   
2   3       Gunnar Nielsen Aaby    M   24.0    NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye    M   34.0    NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink    F   21.0  185.0    82.0     Netherlands   

   CON        Jogos   Ano Temporada     Cidade        Esporte  \
0  CHN  1992 Summer  1992    Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012    Summer     London           Judo   
2  DEN  1920 Summer  1920    Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900    Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988    Winter    Calgary  Speed Skating   

                             Evento Medalha  
0       Basketball Men's Basketball     NaN  
1      Judo Men's Extra-Lightweight     NaN  
2           Football Men's Football     NaN  
3       Tug-Of-War Men's Tug-Of-War    Gold  
4  Speed Skating Women's 500 metres     NaN

In [58]:
# e tambem se você quiser te como pegar uma coluna especifaca
altura = df["Weight"].head(10)
altura

# link da kaggle:
# https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results

0    80.0
1    60.0
2     NaN
3     NaN
4    82.0
5    82.0
6    82.0
7    82.0
8    82.0
9    82.0
Name: Weight, dtype: float64

In [62]:
# agora caso queira mais de uma coluna
altura2 = df[['Weight','Height']].head() # coloque mais um colchte , o nome da outra coluna
altura2 

Weight  Height
0    80.0   180.0
1    60.0   170.0
2     NaN     NaN
3     NaN     NaN
4    82.0   185.0

In [68]:
#  localizando pegando uma coluna especifica
df.loc[1]

ID                                   2
Name                          A Lamusi
Sex                                  M
Age                                 23
Height                             170
Weight                              60
Team                             China
NOC                                CHN
Games                      2012 Summer
Year                              2012
Season                          Summer
City                            London
Sport                             Judo
Event     Judo Men's Extra-Lightweight
Medal                              NaN
Name: 1, dtype: object

In [69]:
# pode ser qualquer uma
df.loc[2]

ID                              3
Name          Gunnar Nielsen Aaby
Sex                             M
Age                            24
Height                        NaN
Weight                        NaN
Team                      Denmark
NOC                           DEN
Games                 1920 Summer
Year                         1920
Season                     Summer
City                    Antwerpen
Sport                    Football
Event     Football Men's Football
Medal                         NaN
Name: 2, dtype: object

In [84]:
# podendo pegar mais de uma, mas nesse caso seria melhor o head()
 df.loc[0:2]

ID                 Name Sex   Age  Height  Weight     Team  NOC  \
0   1            A Dijiang   M  24.0   180.0    80.0    China  CHN   
1   2             A Lamusi   M  23.0   170.0    60.0    China  CHN   
2   3  Gunnar Nielsen Aaby   M  24.0     NaN     NaN  Denmark  DEN   

         Games  Year  Season       City       Sport  \
0  1992 Summer  1992  Summer  Barcelona  Basketball   
1  2012 Summer  2012  Summer     London        Judo   
2  1920 Summer  1920  Summer  Antwerpen    Football   

                          Event Medal  
0   Basketball Men's Basketball   NaN  
1  Judo Men's Extra-Lightweight   NaN  
2       Football Men's Football   NaN

In [87]:
# como de se esperar tem como pular de um em um
df.loc[0:2:2] 

ID                 Name Sex   Age  Height  Weight     Team  NOC  \
0   1            A Dijiang   M  24.0   180.0    80.0    China  CHN   
2   3  Gunnar Nielsen Aaby   M  24.0     NaN     NaN  Denmark  DEN   

         Games  Year  Season       City       Sport  \
0  1992 Summer  1992  Summer  Barcelona  Basketball   
2  1920 Summer  1920  Summer  Antwerpen    Football   

                         Event Medal  
0  Basketball Men's Basketball   NaN  
2      Football Men's Football   NaN

In [89]:
# como pegar uma informação especifica, como pegar linhas que tem apenas um time. pra isso o loc[]
Chineses = df['Team'] == 'China'
df.loc[Chineses].head() # pronto agora você pode focar em um time especifico

ID           Name Sex   Age  Height  Weight   Team  NOC        Games  \
0        1      A Dijiang   M  24.0   180.0    80.0  China  CHN  1992 Summer   
1        2       A Lamusi   M  23.0   170.0    60.0  China  CHN  2012 Summer   
1072   602  Abudoureheman   M  22.0   182.0    75.0  China  CHN  2000 Summer   
2611  1463      Ai Linuer   M  25.0   160.0    62.0  China  CHN  2004 Summer   
2612  1464      Ai Yanhan   F  14.0   168.0    54.0  China  CHN  2016 Summer   

      Year  Season            City       Sport  \
0     1992  Summer       Barcelona  Basketball   
1     2012  Summer          London        Judo   
1072  2000  Summer          Sydney      Boxing   
2611  2004  Summer          Athina   Wrestling   
2612  2016  Summer  Rio de Janeiro    Swimming   

                                         Event Medal  
0                  Basketball Men's Basketball   NaN  
1                 Judo Men's Extra-Lightweight   NaN  
1072                 Boxing Men's Middleweight   NaN  
2611  Wrestling Men's Lightweight, Greco-Roman   NaN  
2612     Swimming Women's 200 metres Freestyle   NaN

In [93]:
# e pra ser mais especifico você pode pegar as colunas tambem
df.loc[Chineses,['City','Sport','Age','Team']] #agora voce pode ver 

City       Sport   Age   Team
0            Barcelona  Basketball  24.0  China
1               London        Judo  23.0  China
1072            Sydney      Boxing  22.0  China
2611            Athina   Wrestling  25.0  China
2612    Rio de Janeiro    Swimming  14.0  China
...                ...         ...   ...    ...
270443          London    Football   NaN  China
270444  Rio de Janeiro  Basketball  20.0  China
270445     Los Angeles   Athletics  28.0  China
270559  Rio de Janeiro    Swimming  26.0  China
270822     Los Angeles  Volleyball  21.0  China

[4975 rows x 4 columns]

In [96]:
Chineses.count()

271116

In [98]:
df.count(C)

TypeError: 'Series' objects are mutable, thus they cannot be hashed

- ###  DataFrame e Dicio

In [7]:
# criando dataframe e dicionario
alunos = {"Nome":["Laura","Lauricio","Marcelo","Mariana","Clark Quente","Lex Luter Soares"],
         "Nota":[7, 6, 4.5, 6.9, 8, 11],
          "Media":6.0,
         "Aprovado":["Sim","Sim","Não","Sim","Sim","COMO?!?"]}
print(alunos)

{'Nome': ['Laura', 'Lauricio', 'Marcelo', 'Mariana', 'Clark Quente', 'Lex Luter Soares'], 'Nota': [7, 6, 4.5, 6.9, 8, 11], 'Media': 6.0, 'Aprovado': ['Sim', 'Sim', 'Não', 'Sim', 'Sim', 'COMO?!?']}


In [8]:
# como você pode ver se a Nota for menor que 6 ele nao sera aprovado 
df = pd.DataFrame(alunos)
df

Nome  Nota  Media Aprovado
0             Laura   7.0    6.0      Sim
1          Lauricio   6.0    6.0      Sim
2           Marcelo   4.5    6.0      Não
3           Mariana   6.9    6.0      Sim
4      Clark Quente   8.0    6.0      Sim
5  Lex Luter Soares  11.0    6.0  COMO?!?

In [9]:
print(df,"(lex luter na dando infartando os professores)[isso ainda na escolhina]")

               Nome  Nota  Media Aprovado
0             Laura   7.0    6.0      Sim
1          Lauricio   6.0    6.0      Sim
2           Marcelo   4.5    6.0      Não
3           Mariana   6.9    6.0      Sim
4      Clark Quente   8.0    6.0      Sim
5  Lex Luter Soares  11.0    6.0  COMO?!? (lex luter na dando infartando os professores)[isso ainda na escolhina]


In [25]:
# .shape olha o quantidade de linhas e colunas.
df.shape

(6, 4)

In [27]:
pe=df.describe()
round(pe)

Nota  Media
count   6.0    6.0
mean    7.0    6.0
std     2.0    0.0
min     4.0    6.0
25%     6.0    6.0
50%     7.0    6.0
75%     8.0    6.0
max    11.0    6.0

In [28]:
pe

Nota  Media
count   6.000000    6.0
mean    7.233333    6.0
std     2.187845    0.0
min     4.500000    6.0
25%     6.225000    6.0
50%     6.950000    6.0
75%     7.750000    6.0
max    11.000000    6.0

In [46]:
# mais um comando legal .info() basicamente ele da informações
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Nome      6 non-null      object 
 1   Nota      6 non-null      float64
 2   Media     6 non-null      float64
 3   Aprovado  6 non-null      object 
dtypes: float64(2), object(2)
memory usage: 320.0+ bytes


- ### comandos dahora de dicionarios

In [36]:
alunos.keys()

dict_keys(['Nome', 'Nota', 'Media', 'Aprovado'])

In [38]:
alunos.values()

dict_values([['Laura', 'Lauricio', 'Marcelo', 'Mariana', 'clark Quente', 'Lex Luter Soares'], [7, 6, 4.5, 6.9, 8, 11], 6.0, ['Sim', 'Sim', 'Não', 'Sim', 'Sim', 'COMO?!?']])

In [39]:
alunos.items()

dict_items([('Nome', ['Laura', 'Lauricio', 'Marcelo', 'Mariana', 'clark Quente', 'Lex Luter Soares']), ('Nota', [7, 6, 4.5, 6.9, 8, 11]), ('Media', 6.0), ('Aprovado', ['Sim', 'Sim', 'Não', 'Sim', 'Sim', 'COMO?!?'])])

### pandas e numpy
- Series e Array

In [11]:
# ele mostra tudo da lista em apenas uma coluna
obj = pd.Series([1,2,3,9,8,7,6,5,4])
obj

0    1
1    2
2    3
3    9
4    8
5    7
6    6
7    5
8    4
dtype: int64

In [15]:
# como você pode ver não tem coluna
obj.shape

(9,)

In [36]:
import numpy as np
# dica: se no seu deu errado é porque o numero de objetos na 1º tupla não é o mesmo na 2º
aray = np.array([(2,4,6,8,9,123),(1,3,5,7,9,594)]) # bi-dimensional  
aray2 = np.array([("limão"),("com marcuja")]) # bi-dimensional str
aray1 = np.array([1,2,3,4,5,6,7,8,9]) # uni-dimendsinal 
print(aray)
print(aray2)
print(aray1)

[[  2   4   6   8   9 123]
 [  1   3   5   7   9 594]]
['limão' 'com marcuja']
[1 2 3 4 5 6 7 8 9]


In [42]:
# usando pandas e numpy juntos
obj2 = pd.Series(aray1) 
print(obj2)
# obj3 = pd.Series(aray), tome cuidado pois ha limitações se usado com um array bi-dimen.
# print(obj3) dara error


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32


In [45]:
# como pde ver faz o mesmo que o array do numpy mas continua sendo em uma dimensao
obj3 = pd.array(aray1)
print(obj3)

<IntegerArray>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
Length: 9, dtype: Int32
